from graphviz import Digraph
g = Digraph('studyplan', filename='studyplan.gv')
g.attr('graph', fontname='Helvetica')
g.attr('node', fontname='Helvetica')
c0 = Digraph('cluster_0')
c0.body.append('label = "LEGEND"')
c0.body.append('color=lightgrey')
c0.node_attr.update(style='filled', color='white')
c0.edge_attr.update(color='white')
c0.node('Semester 6', color='plum')
c0.node('Semester 7')
c0.node('Semester 3', color='peachpuff')
c0.node('Semester 4', color='darkseagreen')
c0.node('Semester 5', color='lightblue')
c0.node('Completed', color='grey')
c0.node('Semester 1', color='pink')
c0.node('Semester 2', color='lightsalmon')
c0.node('Semester 8')
c0.edge('Semester 6', 'Semester 7')
c0.edge('Semester 7', 'Semester 8')
c0.edge('Semester 3', 'Semester 4')
c0.edge('Semester 4', 'Semester 5')
c0.edge('Completed', 'Semester 1')
c0.edge('Semester 1', 'Semester 2')
c0.body.append('label = "LEGEND"')

c1 = Digraph('cluster_1')
c1.body.append('color=aliceblue')
c1.body.append('style=filled')
c1.body.append('labelloc = "b"')
c1.body.append('label = "Science and Math Electives [required]"')
c1.edge('MATH 150B', 'MATH 250A')
c1.edge('PHYS 225', 'PHYS 225L', '', arrowhead='dot', arrowtail='dot', dir='both')
c1.edge('PHYS 225', 'PHYS 226')
c1.edge('PHYS 226', 'PHYS 226L', '', arrowhead='dot', arrowtail='dot', dir='both')
c1.node('MATH 150A')
c1.node('MATH 250A')
c1.node('MATH 338')


c2 = Digraph('cluster_2')
c2.body.append('color=aliceblue')
c2.body.append('style=filled')
c2.body.append('labelloc = "b"')
c2.body.append('label = "Internet & Enterprise (IE) Computing"')
c2.edge('CPSC 332', 'CPSC 431')
c2.edge('CPSC 332', 'CPSC 473')
c2.edge('CPSC 223', 'CPSC 476')
c2.edge('CPSC 351', 'CPSC 476')


# taken
g.attr('node', style='filled', color='grey')
g.node('MATH 270A')
g.node('MATH 270B')

# semester: 1
g.attr('node', style='filled', color='pink')
g.node('CPSC 120')
g.node('ENGL 101')
g.node('MATH 150A')
g.node('PHYS 225')
g.node('CPSC 121')

# semester: 2
g.attr('node', style='filled', color='lightsalmon')
g.node('MATH 150B')
g.node('PHYS 225L')
g.node('PHYS 226')
g.node('CPSC 131')
g.node('MATH 338')

# semester: 3
g.attr('node', style='filled', color='peachpuff')
g.node('MATH 250A')
g.node('PHYS 226L')
g.node('CPSC 223')
g.node('CPSC 240')
g.node('CPSC 254')
g.node('CPSC 311')

# semester: 4
g.attr('node', style='filled', color='darkseagreen')
g.node('CPSC 332')
g.node('CPSC 440')
g.node('CPSC 301')
g.node('CPSC 351')
g.node('CPSC 315')

# semester: 5
g.attr('node', style='filled', color='lightblue')
g.node('CPSC 431')
g.node('CPSC 473')
g.node('CPSC 323')
g.node('CPSC 335')
g.node('CPSC 362')

# semester: 6
g.attr('node', style='filled', color='plum')
g.node('CPSC 471')
g.node('CPSC 476')
g.node('CPSC 481')


# Core Courses [required]
g.edge('CPSC 120', 'CPSC 121', color='red')
g.edge('CPSC 121', 'CPSC 131', color='red')
g.edge('CPSC 131', 'CPSC 223')
g.edge('CPSC 131', 'CPSC 240')
g.edge('CPSC 131', 'CPSC 254', color='red')
g.edge('CPSC 131', 'CPSC 311')
g.edge('CPSC 131', 'CPSC 332')
g.edge('CPSC 240', 'CPSC 440')
g.edge('CPSC 254', 'CPSC 301', color='red')
g.edge('CPSC 254', 'CPSC 351')
g.edge('CPSC 301', 'CPSC 323')
g.edge('CPSC 301', 'CPSC 335', color='red')
g.edge('CPSC 301', 'CPSC 362')
g.edge('CPSC 311', 'CPSC 315')
g.edge('CPSC 311', 'CPSC 362')
g.edge('CPSC 335', 'CPSC 481')
g.edge('CPSC 351', 'CPSC 471')
g.edge('ENGL 101', 'CPSC 311')
g.edge('MATH 150A', 'MATH 150B', color='red')
g.edge('MATH 150B', 'MATH 338', color='red')
g.edge('MATH 270A', 'CPSC 240')
g.edge('MATH 270A', 'MATH 270B')
g.edge('MATH 270B', 'CPSC 335', color='red')
g.edge('MATH 338', 'CPSC 335', color='red')

g.subgraph(c1)
g.subgraph(c2)
g.subgraph(c0)
g.view()